use wasm_bindgen::prelude::*;
use serde_json;

#[wasm_bindgen]
pub fn generate_css(theme_json: &str) -> String {
    let theme: serde_json::Value = match serde_json::from_str(theme_json) {
        Ok(t) => t,
        Err(_) => return String::from("/* Invalid theme JSON */"),
    };

    let theme_name = theme["name"].as_str().unwrap_or("Untitled Theme");
    
    let mut css = String::from("/* =====================================================\n");
    css.push_str(&format!("   StyloFront Theme Export\n"));
    css.push_str(&format!("   Theme: {}\n", theme_name));
    css.push_str("   Generated by: StyloFront Theme Tool\n");
    css.push_str("   ===================================================== */\n\n");

    // Font imports
    if let Some(fonts) = theme["fonts"].as_object() {
        if let Some(sans) = fonts["sans"].as_object() {
            if let Some(import_url) = sans["importUrl"].as_str() {
                if !import_url.is_empty() {
                    css.push_str(&format!("@import url('{}');\n", import_url));
                }
            }
        }
        if let Some(mono) = fonts["mono"].as_object() {
            if let Some(import_url) = mono["importUrl"].as_str() {
                if !import_url.is_empty() {
                    css.push_str(&format!("@import url('{}');\n", import_url));
                }
            }
        }
    }
    css.push_str("\n");

    // Base Tokens
    css.push_str("/* ---------- Base Tokens (Shared) ---------- */\n");
    css.push_str(":root {\n");
    
    // Spacing
    if let Some(spacing) = theme["baseTokens"]["spacing"].as_array() {
        for token in spacing {
            if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                css.push_str(&format!("  --space-{}: {};\n", name, value));
            }
        }
    }
    
    // Radius
    if let Some(radius) = theme["baseTokens"]["radius"].as_array() {
        for token in radius {
            if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                css.push_str(&format!("  --radius-{}: {};\n", name, value));
            }
        }
    }
    
    // Border Width
    if let Some(border_width) = theme["baseTokens"]["borderWidth"].as_array() {
        for token in border_width {
            if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                css.push_str(&format!("  --border-{}: {};\n", name, value));
            }
        }
    }
    
    // Typography
    if let Some(typography) = theme["baseTokens"]["typography"].as_object() {
        // Font families
        if let Some(sans) = theme["fonts"]["sans"].as_object() {
            if let Some(name) = sans["name"].as_str() {
                css.push_str(&format!("  --font-sans: {}, system-ui, sans-serif;\n", name));
            }
        }
        if let Some(mono) = theme["fonts"]["mono"].as_object() {
            if let Some(name) = mono["name"].as_str() {
                css.push_str(&format!("  --font-mono: {}, monospace;\n", name));
            }
        }
        
        // Font sizes
        if let Some(font_sizes) = typography["fontSizes"].as_array() {
            for token in font_sizes {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    css.push_str(&format!("  --text-{}: {};\n", name, value));
                }
            }
        }
        
        // Line heights
        if let Some(line_heights) = typography["lineHeights"].as_array() {
            for token in line_heights {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    css.push_str(&format!("  --leading-{}: {};\n", name, value));
                }
            }
        }
        
        // Font weights
        if let Some(font_weights) = typography["fontWeights"].as_array() {
            for token in font_weights {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    css.push_str(&format!("  --font-{}: {};\n", name, value));
                }
            }
        }
    }
    
    css.push_str("}\n\n");

    // Light Mode
    css.push_str("/* ---------- Light Mode ---------- */\n");
    css.push_str("[data-theme=\"light\"] {\n");
    
    if let Some(colors) = theme["colors"]["light"].as_object() {
        // Primary
        if let Some(primary) = colors["primary"].as_str() {
            css.push_str(&format!("  --color-primary: {};\n", primary));
        }
        if let Some(primary_fg) = colors["primaryFg"].as_str() {
            css.push_str(&format!("  --color-primary-fg: {};\n", primary_fg));
        }
        
        // Secondary
        if let Some(secondary) = colors["secondary"].as_str() {
            css.push_str(&format!("  --color-secondary: {};\n", secondary));
        }
        if let Some(secondary_fg) = colors["secondaryFg"].as_str() {
            css.push_str(&format!("  --color-secondary-fg: {};\n", secondary_fg));
        }
        
        // Background & Surface
        if let Some(background) = colors["background"].as_str() {
            css.push_str(&format!("  --color-background: {};\n", background));
        }
        if let Some(surface) = colors["surface"].as_str() {
            css.push_str(&format!("  --color-surface: {};\n", surface));
        }
        
        // Text
        if let Some(text) = colors["text"].as_str() {
            css.push_str(&format!("  --color-text: {};\n", text));
        }
        if let Some(muted_text) = colors["mutedText"].as_str() {
            css.push_str(&format!("  --color-muted-text: {};\n", muted_text));
        }
        
        // Border
        if let Some(border) = colors["border"].as_str() {
            css.push_str(&format!("  --color-border: {};\n", border));
        }
        
        // Status colors
        if let Some(success) = colors["success"].as_str() {
            css.push_str(&format!("  --color-success: {};\n", success));
        }
        if let Some(warning) = colors["warning"].as_str() {
            css.push_str(&format!("  --color-warning: {};\n", warning));
        }
        if let Some(error) = colors["error"].as_str() {
            css.push_str(&format!("  --color-error: {};\n", error));
        }
        
        // Custom colors
        if let Some(custom) = colors["custom"].as_array() {
            for color_obj in custom {
                if let (Some(name), Some(value)) = (color_obj["name"].as_str(), color_obj["value"].as_str()) {
                    css.push_str(&format!("  --color-{}: {};\n", name, value));
                }
            }
        }
    }
    
    // Shadows
    if let Some(shadows) = theme["shadows"].as_object() {
        // Default shadows
        if let Some(default_shadows) = shadows["default"].as_array() {
            for token in default_shadows {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    css.push_str(&format!("  --shadow-{}: {};\n", name, value));
                }
            }
        }
        // Custom shadows
        if let Some(custom_shadows) = shadows["custom"].as_array() {
            for token in custom_shadows {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    css.push_str(&format!("  --shadow-{}: {};\n", name, value));
                }
            }
        }
    }
    
    css.push_str("}\n\n");

    // Dark Mode
    css.push_str("/* ---------- Dark Mode ---------- */\n");
    css.push_str("[data-theme=\"dark\"] {\n");
    
    if let Some(colors) = theme["colors"]["dark"].as_object() {
        // Primary
        if let Some(primary) = colors["primary"].as_str() {
            css.push_str(&format!("  --color-primary: {};\n", primary));
        }
        if let Some(primary_fg) = colors["primaryFg"].as_str() {
            css.push_str(&format!("  --color-primary-fg: {};\n", primary_fg));
        }
        
        // Secondary
        if let Some(secondary) = colors["secondary"].as_str() {
            css.push_str(&format!("  --color-secondary: {};\n", secondary));
        }
        if let Some(secondary_fg) = colors["secondaryFg"].as_str() {
            css.push_str(&format!("  --color-secondary-fg: {};\n", secondary_fg));
        }
        
        // Background & Surface
        if let Some(background) = colors["background"].as_str() {
            css.push_str(&format!("  --color-background: {};\n", background));
        }
        if let Some(surface) = colors["surface"].as_str() {
            css.push_str(&format!("  --color-surface: {};\n", surface));
        }
        
        // Text
        if let Some(text) = colors["text"].as_str() {
            css.push_str(&format!("  --color-text: {};\n", text));
        }
        if let Some(muted_text) = colors["mutedText"].as_str() {
            css.push_str(&format!("  --color-muted-text: {};\n", muted_text));
        }
        
        // Border
        if let Some(border) = colors["border"].as_str() {
            css.push_str(&format!("  --color-border: {};\n", border));
        }
        
        // Status colors
        if let Some(success) = colors["success"].as_str() {
            css.push_str(&format!("  --color-success: {};\n", success));
        }
        if let Some(warning) = colors["warning"].as_str() {
            css.push_str(&format!("  --color-warning: {};\n", warning));
        }
        if let Some(error) = colors["error"].as_str() {
            css.push_str(&format!("  --color-error: {};\n", error));
        }
        
        // Custom colors
        if let Some(custom) = colors["custom"].as_array() {
            for color_obj in custom {
                if let (Some(name), Some(value)) = (color_obj["name"].as_str(), color_obj["value"].as_str()) {
                    css.push_str(&format!("  --color-{}: {};\n", name, value));
                }
            }
        }
    }
    
    // Shadows for dark mode
    if let Some(shadows) = theme["shadows"].as_object() {
        // Default shadows
        if let Some(default_shadows) = shadows["default"].as_array() {
            for token in default_shadows {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    css.push_str(&format!("  --shadow-{}: {};\n", name, value));
                }
            }
        }
        // Custom shadows
        if let Some(custom_shadows) = shadows["custom"].as_array() {
            for token in custom_shadows {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    css.push_str(&format!("  --shadow-{}: {};\n", name, value));
                }
            }
        }
    }
    
    css.push_str("}\n");
    css
}

#[wasm_bindgen]
pub fn generate_scss(theme_json: &str) -> String {
    let theme: serde_json::Value = match serde_json::from_str(theme_json) {
        Ok(t) => t,
        Err(_) => return String::from("// Invalid theme JSON"),
    };

    let theme_name = theme["name"].as_str().unwrap_or("Untitled Theme");
    
    let mut scss = String::from("// =====================================================\n");
    scss.push_str(&format!("// StyloFront Theme Export\n"));
    scss.push_str(&format!("// Theme: {}\n", theme_name));
    scss.push_str("// Generated by: StyloFront Theme Tool\n");
    scss.push_str("// =====================================================\n\n");

    // Font imports
    if let Some(fonts) = theme["fonts"].as_object() {
        if let Some(sans) = fonts["sans"].as_object() {
            if let Some(import_url) = sans["importUrl"].as_str() {
                if !import_url.is_empty() {
                    scss.push_str(&format!("@import url('{}');\n", import_url));
                }
            }
        }
        if let Some(mono) = fonts["mono"].as_object() {
            if let Some(import_url) = mono["importUrl"].as_str() {
                if !import_url.is_empty() {
                    scss.push_str(&format!("@import url('{}');\n", import_url));
                }
            }
        }
    }
    scss.push_str("\n");

    // SCSS Variables
    scss.push_str("// Theme SCSS Variables\n");
    scss.push_str("$theme: (\n");
    
    // Light mode colors
    if let Some(colors) = theme["colors"]["light"].as_object() {
        if let Some(primary) = colors["primary"].as_str() {
            scss.push_str(&format!("  primary: {},\n", primary));
        }
        if let Some(primary_fg) = colors["primaryFg"].as_str() {
            scss.push_str(&format!("  primary-fg: {},\n", primary_fg));
        }
        if let Some(secondary) = colors["secondary"].as_str() {
            scss.push_str(&format!("  secondary: {},\n", secondary));
        }
        if let Some(secondary_fg) = colors["secondaryFg"].as_str() {
            scss.push_str(&format!("  secondary-fg: {},\n", secondary_fg));
        }
        if let Some(background) = colors["background"].as_str() {
            scss.push_str(&format!("  background: {},\n", background));
        }
        if let Some(surface) = colors["surface"].as_str() {
            scss.push_str(&format!("  surface: {},\n", surface));
        }
        if let Some(text) = colors["text"].as_str() {
            scss.push_str(&format!("  text: {},\n", text));
        }
        if let Some(muted_text) = colors["mutedText"].as_str() {
            scss.push_str(&format!("  muted-text: {},\n", muted_text));
        }
        if let Some(border) = colors["border"].as_str() {
            scss.push_str(&format!("  border: {},\n", border));
        }
        if let Some(success) = colors["success"].as_str() {
            scss.push_str(&format!("  success: {},\n", success));
        }
        if let Some(warning) = colors["warning"].as_str() {
            scss.push_str(&format!("  warning: {},\n", warning));
        }
        if let Some(error) = colors["error"].as_str() {
            scss.push_str(&format!("  error: {},\n", error));
        }
        
        // Custom colors
        if let Some(custom) = colors["custom"].as_array() {
            for color_obj in custom {
                if let (Some(name), Some(value)) = (color_obj["name"].as_str(), color_obj["value"].as_str()) {
                    scss.push_str(&format!("  {}: {},\n", name, value));
                }
            }
        }
    }
    
    scss.push_str(");\n\n");
    
    // Base Tokens - Spacing
    scss.push_str("// Spacing Tokens\n");
    scss.push_str("$spacing: (\n");
    if let Some(spacing) = theme["baseTokens"]["spacing"].as_array() {
        for token in spacing {
            if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                scss.push_str(&format!("  {}: {},\n", name, value));
            }
        }
    }
    scss.push_str(");\n\n");
    
    // Base Tokens - Radius
    scss.push_str("// Radius Tokens\n");
    scss.push_str("$radius: (\n");
    if let Some(radius) = theme["baseTokens"]["radius"].as_array() {
        for token in radius {
            if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                scss.push_str(&format!("  {}: {},\n", name, value));
            }
        }
    }
    scss.push_str(");\n\n");
    
    // Base Tokens - Typography
    scss.push_str("// Typography Tokens\n");
    if let Some(typography) = theme["baseTokens"]["typography"].as_object() {
        // Font sizes
        scss.push_str("$font-sizes: (\n");
        if let Some(font_sizes) = typography["fontSizes"].as_array() {
            for token in font_sizes {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    scss.push_str(&format!("  {}: {},\n", name, value));
                }
            }
        }
        scss.push_str(");\n\n");
        
        // Line heights
        scss.push_str("$line-heights: (\n");
        if let Some(line_heights) = typography["lineHeights"].as_array() {
            for token in line_heights {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    scss.push_str(&format!("  {}: {},\n", name, value));
                }
            }
        }
        scss.push_str(");\n\n");
        
        // Font weights
        scss.push_str("$font-weights: (\n");
        if let Some(font_weights) = typography["fontWeights"].as_array() {
            for token in font_weights {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    scss.push_str(&format!("  {}: {},\n", name, value));
                }
            }
        }
        scss.push_str(");\n\n");
    }
    
    // Shadows
    scss.push_str("// Shadow Tokens\n");
    scss.push_str("$shadows: (\n");
    if let Some(shadows) = theme["shadows"].as_object() {
        if let Some(default_shadows) = shadows["default"].as_array() {
            for token in default_shadows {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    scss.push_str(&format!("  {}: {},\n", name, value));
                }
            }
        }
        if let Some(custom_shadows) = shadows["custom"].as_array() {
            for token in custom_shadows {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    scss.push_str(&format!("  {}: {},\n", name, value));
                }
            }
        }
    }
    scss.push_str(");\n\n");
    
    // Fonts
    scss.push_str("// Font Families\n");
    scss.push_str("$fonts: (\n");
    if let Some(sans) = theme["fonts"]["sans"].as_object() {
        if let Some(name) = sans["name"].as_str() {
            scss.push_str(&format!("  sans: '{}',\n", name));
        }
    }
    if let Some(mono) = theme["fonts"]["mono"].as_object() {
        if let Some(name) = mono["name"].as_str() {
            scss.push_str(&format!("  mono: '{}',\n", name));
        }
    }
    scss.push_str(");\n\n");
    
    // Dark mode colors
    scss.push_str("$theme-dark: (\n");
    if let Some(colors) = theme["colors"]["dark"].as_object() {
        if let Some(primary) = colors["primary"].as_str() {
            scss.push_str(&format!("  primary: {},\n", primary));
        }
        if let Some(primary_fg) = colors["primaryFg"].as_str() {
            scss.push_str(&format!("  primary-fg: {},\n", primary_fg));
        }
        if let Some(secondary) = colors["secondary"].as_str() {
            scss.push_str(&format!("  secondary: {},\n", secondary));
        }
        if let Some(secondary_fg) = colors["secondaryFg"].as_str() {
            scss.push_str(&format!("  secondary-fg: {},\n", secondary_fg));
        }
        if let Some(background) = colors["background"].as_str() {
            scss.push_str(&format!("  background: {},\n", background));
        }
        if let Some(surface) = colors["surface"].as_str() {
            scss.push_str(&format!("  surface: {},\n", surface));
        }
        if let Some(text) = colors["text"].as_str() {
            scss.push_str(&format!("  text: {},\n", text));
        }
        if let Some(muted_text) = colors["mutedText"].as_str() {
            scss.push_str(&format!("  muted-text: {},\n", muted_text));
        }
        if let Some(border) = colors["border"].as_str() {
            scss.push_str(&format!("  border: {},\n", border));
        }
        if let Some(success) = colors["success"].as_str() {
            scss.push_str(&format!("  success: {},\n", success));
        }
        if let Some(warning) = colors["warning"].as_str() {
            scss.push_str(&format!("  warning: {},\n", warning));
        }
        if let Some(error) = colors["error"].as_str() {
            scss.push_str(&format!("  error: {},\n", error));
        }
        
        // Custom colors
        if let Some(custom) = colors["custom"].as_array() {
            for color_obj in custom {
                if let (Some(name), Some(value)) = (color_obj["name"].as_str(), color_obj["value"].as_str()) {
                    scss.push_str(&format!("  {}: {},\n", name, value));
                }
            }
        }
    }
    
    scss.push_str(");\n");
    scss
}

#[wasm_bindgen]
pub fn generate_sass(theme_json: &str) -> String {
    let theme: serde_json::Value = match serde_json::from_str(theme_json) {
        Ok(t) => t,
        Err(_) => return String::from("// Invalid theme JSON"),
    };

    let theme_name = theme["name"].as_str().unwrap_or("Untitled Theme");
    
    let mut sass = String::from("// =====================================================\n");
    sass.push_str(&format!("// StyloFront Theme Export\n"));
    sass.push_str(&format!("// Theme: {}\n", theme_name));
    sass.push_str("// Generated by: StyloFront Theme Tool\n");
    sass.push_str("// =====================================================\n\n");

    // Font imports
    if let Some(fonts) = theme["fonts"].as_object() {
        if let Some(sans) = fonts["sans"].as_object() {
            if let Some(import_url) = sans["importUrl"].as_str() {
                if !import_url.is_empty() {
                    sass.push_str(&format!("@import url('{}')\n", import_url));
                }
            }
        }
        if let Some(mono) = fonts["mono"].as_object() {
            if let Some(import_url) = mono["importUrl"].as_str() {
                if !import_url.is_empty() {
                    sass.push_str(&format!("@import url('{}')\n", import_url));
                }
            }
        }
    }
    sass.push_str("\n");

    // SASS Variables
    sass.push_str("// Theme SASS Variables\n");
    sass.push_str("$theme: (\n");
    
    // Light mode colors
    if let Some(colors) = theme["colors"]["light"].as_object() {
        if let Some(primary) = colors["primary"].as_str() {
            sass.push_str(&format!("  primary: {}\n", primary));
        }
        if let Some(primary_fg) = colors["primaryFg"].as_str() {
            sass.push_str(&format!("  primary-fg: {}\n", primary_fg));
        }
        if let Some(secondary) = colors["secondary"].as_str() {
            sass.push_str(&format!("  secondary: {}\n", secondary));
        }
        if let Some(secondary_fg) = colors["secondaryFg"].as_str() {
            sass.push_str(&format!("  secondary-fg: {}\n", secondary_fg));
        }
        if let Some(background) = colors["background"].as_str() {
            sass.push_str(&format!("  background: {}\n", background));
        }
        if let Some(surface) = colors["surface"].as_str() {
            sass.push_str(&format!("  surface: {}\n", surface));
        }
        if let Some(text) = colors["text"].as_str() {
            sass.push_str(&format!("  text: {}\n", text));
        }
        if let Some(muted_text) = colors["mutedText"].as_str() {
            sass.push_str(&format!("  muted-text: {}\n", muted_text));
        }
        if let Some(border) = colors["border"].as_str() {
            sass.push_str(&format!("  border: {}\n", border));
        }
        if let Some(success) = colors["success"].as_str() {
            sass.push_str(&format!("  success: {}\n", success));
        }
        if let Some(warning) = colors["warning"].as_str() {
            sass.push_str(&format!("  warning: {}\n", warning));
        }
        if let Some(error) = colors["error"].as_str() {
            sass.push_str(&format!("  error: {}\n", error));
        }
        
        // Custom colors
        if let Some(custom) = colors["custom"].as_array() {
            for color_obj in custom {
                if let (Some(name), Some(value)) = (color_obj["name"].as_str(), color_obj["value"].as_str()) {
                    sass.push_str(&format!("  {}: {}\n", name, value));
                }
            }
        }
    }
    
    sass.push_str(")\n\n");
    
    // Base Tokens - Spacing
    sass.push_str("// Spacing Tokens\n");
    sass.push_str("$spacing: (\n");
    if let Some(spacing) = theme["baseTokens"]["spacing"].as_array() {
        for token in spacing {
            if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                sass.push_str(&format!("  {}: {}\n", name, value));
            }
        }
    }
    sass.push_str(")\n\n");
    
    // Base Tokens - Radius
    sass.push_str("// Radius Tokens\n");
    sass.push_str("$radius: (\n");
    if let Some(radius) = theme["baseTokens"]["radius"].as_array() {
        for token in radius {
            if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                sass.push_str(&format!("  {}: {}\n", name, value));
            }
        }
    }
    sass.push_str(")\n\n");
    
    // Base Tokens - Typography
    sass.push_str("// Typography Tokens\n");
    if let Some(typography) = theme["baseTokens"]["typography"].as_object() {
        // Font sizes
        sass.push_str("$font-sizes: (\n");
        if let Some(font_sizes) = typography["fontSizes"].as_array() {
            for token in font_sizes {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    sass.push_str(&format!("  {}: {}\n", name, value));
                }
            }
        }
        sass.push_str(")\n\n");
        
        // Line heights
        sass.push_str("$line-heights: (\n");
        if let Some(line_heights) = typography["lineHeights"].as_array() {
            for token in line_heights {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    sass.push_str(&format!("  {}: {}\n", name, value));
                }
            }
        }
        sass.push_str(")\n\n");
        
        // Font weights
        sass.push_str("$font-weights: (\n");
        if let Some(font_weights) = typography["fontWeights"].as_array() {
            for token in font_weights {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    sass.push_str(&format!("  {}: {}\n", name, value));
                }
            }
        }
        sass.push_str(")\n\n");
    }
    
    // Shadows
    sass.push_str("// Shadow Tokens\n");
    sass.push_str("$shadows: (\n");
    if let Some(shadows) = theme["shadows"].as_object() {
        if let Some(default_shadows) = shadows["default"].as_array() {
            for token in default_shadows {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    sass.push_str(&format!("  {}: {}\n", name, value));
                }
            }
        }
        if let Some(custom_shadows) = shadows["custom"].as_array() {
            for token in custom_shadows {
                if let (Some(name), Some(value)) = (token["name"].as_str(), token["value"].as_str()) {
                    sass.push_str(&format!("  {}: {}\n", name, value));
                }
            }
        }
    }
    sass.push_str(")\n\n");
    
    // Fonts
    sass.push_str("// Font Families\n");
    sass.push_str("$fonts: (\n");
    if let Some(sans) = theme["fonts"]["sans"].as_object() {
        if let Some(name) = sans["name"].as_str() {
            sass.push_str(&format!("  sans: '{}'\n", name));
        }
    }
    if let Some(mono) = theme["fonts"]["mono"].as_object() {
        if let Some(name) = mono["name"].as_str() {
            sass.push_str(&format!("  mono: '{}'\n", name));
        }
    }
    sass.push_str(")\n\n");
    
    // Dark mode colors
    sass.push_str("$theme-dark: (\n");
    if let Some(colors) = theme["colors"]["dark"].as_object() {
        if let Some(primary) = colors["primary"].as_str() {
            sass.push_str(&format!("  primary: {}\n", primary));
        }
        if let Some(primary_fg) = colors["primaryFg"].as_str() {
            sass.push_str(&format!("  primary-fg: {}\n", primary_fg));
        }
        if let Some(secondary) = colors["secondary"].as_str() {
            sass.push_str(&format!("  secondary: {}\n", secondary));
        }
        if let Some(secondary_fg) = colors["secondaryFg"].as_str() {
            sass.push_str(&format!("  secondary-fg: {}\n", secondary_fg));
        }
        if let Some(background) = colors["background"].as_str() {
            sass.push_str(&format!("  background: {}\n", background));
        }
        if let Some(surface) = colors["surface"].as_str() {
            sass.push_str(&format!("  surface: {}\n", surface));
        }
        if let Some(text) = colors["text"].as_str() {
            sass.push_str(&format!("  text: {}\n", text));
        }
        if let Some(muted_text) = colors["mutedText"].as_str() {
            sass.push_str(&format!("  muted-text: {}\n", muted_text));
        }
        if let Some(border) = colors["border"].as_str() {
            sass.push_str(&format!("  border: {}\n", border));
        }
        if let Some(success) = colors["success"].as_str() {
            sass.push_str(&format!("  success: {}\n", success));
        }
        if let Some(warning) = colors["warning"].as_str() {
            sass.push_str(&format!("  warning: {}\n", warning));
        }
        if let Some(error) = colors["error"].as_str() {
            sass.push_str(&format!("  error: {}\n", error));
        }
        
        // Custom colors
        if let Some(custom) = colors["custom"].as_array() {
            for color_obj in custom {
                if let (Some(name), Some(value)) = (color_obj["name"].as_str(), color_obj["value"].as_str()) {
                    sass.push_str(&format!("  {}: {}\n", name, value));
                }
            }
        }
    }
    
    sass.push_str(")\n");
    sass
}

#[wasm_bindgen]
pub fn generate_json(theme_json: &str) -> String {
    let theme: serde_json::Value = match serde_json::from_str(theme_json) {
        Ok(t) => t,
        Err(_) => return String::from("{}"),
    };
    
    serde_json::to_string_pretty(&theme).unwrap_or_else(|_| String::from("{}"))
}

